### ISSUE TITLE
Logo-coloring

### ISSUE THREAD

**Issue by dimitrymlr** [Scopeweb/wp-scopeweb#3]
As of right now, when navigating to https://staging.scopeweb.nyc/case-studies/ the logo won't display correctly. This is because by default, it loads the base.twig which has the following code added:

`<div class="logo-left text-light" id="logo">`

https://github.com/Scopeweb/wp-scopeweb/blob/master/templates/base.twig#L20 is where this piece of code can be found. With the class text-light, it will load the light logo by default which causes it to become invisible on the case-studies page.

**Comment by MrDemonWolf** [comment]
Should be fixed with a custom if statement.
