### ISSUE TITLE
Footer social links

### ISSUE THREAD

**Issue by dimitrymlr** [Scopeweb/wp-scopeweb#8]
Footer social links for Facebook, Twitter, and Instagram are missing two things:

- target="_blank"
- rel="noreferrer"

**Comment by dimitrymlr** [comment]
Footer social links are also missing the / behind the URLs for the case-studies.

For example:

`<a href="{{ site.link }}/case-studies/ultrabse">Ultrabse</a>` would need to be come: `<a href="{{ site.link }}/case-studies/ultrabse**/**">Ultrabse</a>`

**Comment by MrDemonWolf** [comment]
Fixed.
